### ISSUE TITLE
What does 0x90 mean?

### ISSUE THREAD

**Issue by skynet0dev** [keijiro/unity-smf-test#1]
Hi there is a piece of code in the example:
```C# 
(m.status & 0xf0) == 0x90) 
 if (m.data1 == 0x24)
```
do not tell me what does this `0xf0` mean or is it `0x24`? thanks!

**Comment by keijiro** [comment]
That's just checking if the message carries C2 note on. See the MIDI specification for details.

https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
